$t=Get-Date -Format g
$a=Invoke-RestMethod -Uri https://api.github.com/emojis
$a.psobject.properties | foreach {
    $count=$count+1
}
$c="This list is generated by the script **C:\Data\GitHub\Personal\Scripts\GitHub-Generate-Emoji.ps1**. You might want to run it regularly to keep it current.`r`r**Emoji count:** $count. **Last collected:** $t`r`r| Image | Code |`r| --- | --- |"
$c | Out-File -FilePath 'C:\Data\GitHub\Personal\GitHub\Root\Files\Emojis.md' -Force
$a.psobject.properties | foreach {
    $b="| :" + $_.name + ": | ``:" + $_.name + ":`` |"
    $b # output to screen for testing.
    $b | Out-File -FilePath 'C:\Data\GitHub\Personal\GitHub\Root\Files\Emojis.md' -Append
}